### ISSUE TITLE
Error finding 2.5.1 bottle and building 2.5.1 from source

### ISSUE THREAD

**Issue by myleshorton** [NSIS-Dev/homebrew-makensis#4]
Getting this -- guessing it's an issue with clang versus gcc?

> $ brew link makensis@2.51
Error: No such keg: /usr/local/Cellar/makensis@2.51
[lantern-build ((5.4.6))]$ brew install makensis@2.51
==> Installing makensis@2.51 from nsis-dev/makensis
==> Downloading https://homebrew.bintray.com/bottles-makensis/makensis@2.51-2.51.mojave.bottle.tar.gz

> curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "makensis@2.51"
Download failed: https://homebrew.bintray.com/bottles-makensis/makensis@2.51-2.51.mojave.bottle.tar.gz
Warning: Bottle installation failed: building from source.
==> Downloading https://downloads.sourceforge.net/project/nsis/NSIS%202/2.51/nsis-2.51-src.tar.bz2
Already downloaded: /Users/afisk/Library/Caches/Homebrew/downloads/d4cecc7194896838d0daf23b76d9a91cb586275c2c5a479fac7f77eac6fd1ce8--nsis-2.51-src.tar.bz2
==> Patching
patching file SCons/config.py
==> scons makensis PREFIX_DOC=/usr/local/Cellar/makensis@2.51/2.51/share/nsis/Docs SKIPUTILS=Makensisw,NSIS Menu,zip2exe STRIP=0 VERSION=2.51
Last 15 lines from /Users/afisk/Library/Logs/Homebrew/makensis@2.51/01.scons:
scons: warning: The build_dir keyword has been deprecated; use the variant_dir keyword instead.
File "/private/tmp/makensis@2.51-20190908-57773-17pe9ms/nsis-2.51-src/SConstruct", line 674, in <module>
Checking for C library dl... no
Checking for C library gdi32... no
Checking for C library iconv... no
Checking for C library pthread... no
Checking for C library user32... no
Checking for C++ library cppunit... no
scons: done reading SConscript files.
scons: Building targets ...
/usr/bin/clang++ -stdlib=libstdc++ -o build/release/makensis/build.o -c -Wno-non-virtual-dtor -Wall -O2 -DNSISCALL=__attribute__((__stdcall__)) -D__BIG_ENDIAN__ -D_WIN32_IE=0x0500 -Ibuild/release/config Source/build.cpp
sh: -c: line 0: syntax error near unexpected token `('
sh: -c: line 0: `/usr/bin/clang++ -stdlib=libstdc++ -o "build/release/makensis/build.o" -c -Wno-non-virtual-dtor -Wall -O2 -DNSISCALL=__attribute__((__stdcall__)) -D__BIG_ENDIAN__ -D_WIN32_IE=0x0500 -Ibuild/release/config "Source/build.cpp"'
scons: *** [build/release/makensis/build.o] Error 2
scons: building terminated because of errors.

**Comment by idleberg** [comment]
Hmm. I had a look at the [old Formula](https://github.com/Homebrew/homebrew-core/blob/e04f255fe501984b251d61e56a63ee58fefdcf4a/Formula/makensis.rb), but I don't see anything unusual.

**Comment by iwege** [comment]
some error here
