### ISSUE TITLE
Installing with additional options --with-advanced-logging fails

### ISSUE THREAD

**Issue by ustun** [NSIS-Dev/homebrew-makensis#5]
After I execute

`
brew install makensis --with-advanced-logging --with-large-strings
`

I get the following:

`Error: invalid option: --with-advanced-logging`

Has brew completely removed the ability to provide options for formula, or should I be executing another command?

**Comment by idleberg** [comment]
You are trying to install the `makensis` formula from `homebrew-core`. This tap only provides versions formulas, you need to install as follows:

```sh
brew install makensis@3.05 --with-advanced-logging --with-large-strings
```

**Comment by ustun** [comment]
Thank you very much @idleberg , that worked. I opened a PR that adds that info to the README.
