### ISSUE TITLE
Location of Stubs

### ISSUE THREAD

**Issue by adamretter** [NSIS-Dev/homebrew-makensis#7]
If you install homebrew within a user's directory, perhaps because you do not have admin access. The the root of homebrew is something like `/Users/username/homebrew` as opposed to `/usr/local`.

When you then run `makensis` you get an error like:

```
Error: reading stub "/usr/local/share/nsis/Stubs/zlib-x86-ansi"
Error initalizing CEXEBuild: error setting default stub
```

However, the stub file is available but it is located in: `/Users/username/homebrew/share/nsis/Stubs/zlib-x86-ansi`.

Is it possible to build the Homebrew NSIS package so that it doesn't use a fixed path for the Stubs, but rather expects them to be relative to the homebrew prefix or makensis binary?

I did see mention of a compile option `NSIS_CONFIG_CONST_DATA_PATH`, but I am not certain that would help.

**Comment by idleberg** [comment]
I will follow whatever is use in the official formula, so you might want to suggest it its repository:

https://github.com/Homebrew/homebrew-core/blob/master/Formula/makensis.rb

**Comment by idleberg** [comment]
I hope I didn't discourage in any way. I think this is a good idea, but it should be posted in the official Formular first, before I follow its example.

**Comment by adamretter** [comment]
@idleberg Not at all. I am afraid I just haven't had time to look further into it
